//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({
    providedIn: 'root'
})
export class AuthClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    register(request: RegisterRequestDTO): Observable<FileResponse> {
        let url_ = this.baseUrl + "/api/Auth/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRegister(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRegister(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FileResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FileResponse>;
        }));
    }

    protected processRegister(response: HttpResponseBase): Observable<FileResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return _observableOf({ fileName: fileName, data: responseBlob as any, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    login(request: LoginRequestDTO): Observable<FileResponse> {
        let url_ = this.baseUrl + "/api/Auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processLogin(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processLogin(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FileResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FileResponse>;
        }));
    }

    protected processLogin(response: HttpResponseBase): Observable<FileResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return _observableOf({ fileName: fileName, data: responseBlob as any, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    logout(): Observable<FileResponse> {
        let url_ = this.baseUrl + "/api/Auth/logout";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/octet-stream"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processLogout(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processLogout(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FileResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FileResponse>;
        }));
    }

    protected processLogout(response: HttpResponseBase): Observable<FileResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return _observableOf({ fileName: fileName, data: responseBlob as any, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class InvoiceItemsClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    updateInvoiceItem(id: number, dto: InvoiceItemUpdateDTO): Observable<InvoiceItemDTO> {
        let url_ = this.baseUrl + "/api/invoiceitems/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateInvoiceItem(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateInvoiceItem(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<InvoiceItemDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<InvoiceItemDTO>;
        }));
    }

    protected processUpdateInvoiceItem(response: HttpResponseBase): Observable<InvoiceItemDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = InvoiceItemDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    deleteInvoiceItem(id: number): Observable<FileResponse> {
        let url_ = this.baseUrl + "/api/invoiceitems/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/octet-stream"
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeleteInvoiceItem(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeleteInvoiceItem(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FileResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FileResponse>;
        }));
    }

    protected processDeleteInvoiceItem(response: HttpResponseBase): Observable<FileResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return _observableOf({ fileName: fileName, data: responseBlob as any, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class InvoicesClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getInvoices(invoiceNumber_Operator?: ConditionType | null | undefined, invoiceNumber_Values?: string[] | undefined, customerName_Operator?: ConditionType | null | undefined, customerName_Values?: string[] | undefined, customerBusinessId_Operator?: ConditionType | null | undefined, customerBusinessId_Values?: string[] | undefined, issueDate_Operator?: ConditionType | null | undefined, issueDate_Values?: string[] | undefined, dueDate_Operator?: ConditionType | null | undefined, dueDate_Values?: string[] | undefined, description_Operator?: ConditionType | null | undefined, description_Values?: string[] | undefined, sortBy?: string | null | undefined, direction?: SortDirection | undefined, pageNumber?: number | undefined, pageSize?: number | undefined): Observable<PagedResponseOfListOfInvoiceDTO> {
        let url_ = this.baseUrl + "/api/invoices?";
        if (invoiceNumber_Operator !== undefined && invoiceNumber_Operator !== null)
            url_ += "InvoiceNumber.Operator=" + encodeURIComponent("" + invoiceNumber_Operator) + "&";
        if (invoiceNumber_Values === null)
            throw new globalThis.Error("The parameter 'invoiceNumber_Values' cannot be null.");
        else if (invoiceNumber_Values !== undefined)
            invoiceNumber_Values && invoiceNumber_Values.forEach(item => { url_ += "InvoiceNumber.Values=" + encodeURIComponent("" + item) + "&"; });
        if (customerName_Operator !== undefined && customerName_Operator !== null)
            url_ += "CustomerName.Operator=" + encodeURIComponent("" + customerName_Operator) + "&";
        if (customerName_Values === null)
            throw new globalThis.Error("The parameter 'customerName_Values' cannot be null.");
        else if (customerName_Values !== undefined)
            customerName_Values && customerName_Values.forEach(item => { url_ += "CustomerName.Values=" + encodeURIComponent("" + item) + "&"; });
        if (customerBusinessId_Operator !== undefined && customerBusinessId_Operator !== null)
            url_ += "CustomerBusinessId.Operator=" + encodeURIComponent("" + customerBusinessId_Operator) + "&";
        if (customerBusinessId_Values === null)
            throw new globalThis.Error("The parameter 'customerBusinessId_Values' cannot be null.");
        else if (customerBusinessId_Values !== undefined)
            customerBusinessId_Values && customerBusinessId_Values.forEach(item => { url_ += "CustomerBusinessId.Values=" + encodeURIComponent("" + item) + "&"; });
        if (issueDate_Operator !== undefined && issueDate_Operator !== null)
            url_ += "IssueDate.Operator=" + encodeURIComponent("" + issueDate_Operator) + "&";
        if (issueDate_Values === null)
            throw new globalThis.Error("The parameter 'issueDate_Values' cannot be null.");
        else if (issueDate_Values !== undefined)
            issueDate_Values && issueDate_Values.forEach(item => { url_ += "IssueDate.Values=" + encodeURIComponent("" + item) + "&"; });
        if (dueDate_Operator !== undefined && dueDate_Operator !== null)
            url_ += "DueDate.Operator=" + encodeURIComponent("" + dueDate_Operator) + "&";
        if (dueDate_Values === null)
            throw new globalThis.Error("The parameter 'dueDate_Values' cannot be null.");
        else if (dueDate_Values !== undefined)
            dueDate_Values && dueDate_Values.forEach(item => { url_ += "DueDate.Values=" + encodeURIComponent("" + item) + "&"; });
        if (description_Operator !== undefined && description_Operator !== null)
            url_ += "Description.Operator=" + encodeURIComponent("" + description_Operator) + "&";
        if (description_Values === null)
            throw new globalThis.Error("The parameter 'description_Values' cannot be null.");
        else if (description_Values !== undefined)
            description_Values && description_Values.forEach(item => { url_ += "Description.Values=" + encodeURIComponent("" + item) + "&"; });
        if (sortBy !== undefined && sortBy !== null)
            url_ += "SortBy=" + encodeURIComponent("" + sortBy) + "&";
        if (direction === null)
            throw new globalThis.Error("The parameter 'direction' cannot be null.");
        else if (direction !== undefined)
            url_ += "Direction=" + encodeURIComponent("" + direction) + "&";
        if (pageNumber === null)
            throw new globalThis.Error("The parameter 'pageNumber' cannot be null.");
        else if (pageNumber !== undefined)
            url_ += "PageNumber=" + encodeURIComponent("" + pageNumber) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetInvoices(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetInvoices(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<PagedResponseOfListOfInvoiceDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<PagedResponseOfListOfInvoiceDTO>;
        }));
    }

    protected processGetInvoices(response: HttpResponseBase): Observable<PagedResponseOfListOfInvoiceDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PagedResponseOfListOfInvoiceDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    createInvoice(dto: InvoiceCreateDTO): Observable<InvoiceDTO> {
        let url_ = this.baseUrl + "/api/invoices";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateInvoice(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateInvoice(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<InvoiceDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<InvoiceDTO>;
        }));
    }

    protected processCreateInvoice(response: HttpResponseBase): Observable<InvoiceDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = InvoiceDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    updateInvoice(id: number, dto: InvoiceUpdateDTO): Observable<InvoiceDTO> {
        let url_ = this.baseUrl + "/api/invoices/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateInvoice(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateInvoice(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<InvoiceDTO>;
                }
            } else
                return _observableThrow(response_) as any as Observable<InvoiceDTO>;
        }));
    }

    protected processUpdateInvoice(response: HttpResponseBase): Observable<InvoiceDTO> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = InvoiceDTO.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    deleteInvoice(id: number): Observable<FileResponse> {
        let url_ = this.baseUrl + "/api/invoices/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/octet-stream"
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeleteInvoice(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeleteInvoice(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FileResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FileResponse>;
        }));
    }

    protected processDeleteInvoice(response: HttpResponseBase): Observable<FileResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return _observableOf({ fileName: fileName, data: responseBlob as any, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class InvoicesSpecClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getInvoices(search?: string | undefined, status?: InvoiceStatus | null | undefined, customerName?: string | null | undefined, sort?: string | null | undefined, pageIndex?: number | undefined, pageSize?: number | undefined): Observable<PaginationOfInvoice> {
        let url_ = this.baseUrl + "/api/InvoicesSpec?";
        if (search === null)
            throw new globalThis.Error("The parameter 'search' cannot be null.");
        else if (search !== undefined)
            url_ += "Search=" + encodeURIComponent("" + search) + "&";
        if (status !== undefined && status !== null)
            url_ += "Status=" + encodeURIComponent("" + status) + "&";
        if (customerName !== undefined && customerName !== null)
            url_ += "CustomerName=" + encodeURIComponent("" + customerName) + "&";
        if (sort !== undefined && sort !== null)
            url_ += "Sort=" + encodeURIComponent("" + sort) + "&";
        if (pageIndex === null)
            throw new globalThis.Error("The parameter 'pageIndex' cannot be null.");
        else if (pageIndex !== undefined)
            url_ += "PageIndex=" + encodeURIComponent("" + pageIndex) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetInvoices(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetInvoices(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<PaginationOfInvoice>;
                }
            } else
                return _observableThrow(response_) as any as Observable<PaginationOfInvoice>;
        }));
    }

    protected processGetInvoices(response: HttpResponseBase): Observable<PaginationOfInvoice> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PaginationOfInvoice.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class RegisterRequestDTO implements IRegisterRequestDTO {
    username?: string;
    password?: string;

    constructor(data?: IRegisterRequestDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.username = _data["username"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): RegisterRequestDTO {
        data = typeof data === 'object' ? data : {};
        let result = new RegisterRequestDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["username"] = this.username;
        data["password"] = this.password;
        return data;
    }
}

export interface IRegisterRequestDTO {
    username?: string;
    password?: string;
}

export class LoginRequestDTO implements ILoginRequestDTO {
    username?: string;
    password?: string;

    constructor(data?: ILoginRequestDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.username = _data["username"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginRequestDTO {
        data = typeof data === 'object' ? data : {};
        let result = new LoginRequestDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["username"] = this.username;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginRequestDTO {
    username?: string;
    password?: string;
}

export class InvoiceItemDTO implements IInvoiceItemDTO {
    id?: number;
    description?: string;
    unit?: string;
    quantity?: number;
    unitPrice?: number;
    vatRate?: number;
    invoiceId?: number;
    rowVersion?: string;
    netAmount?: number;
    grossAmount?: number;

    constructor(data?: IInvoiceItemDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.description = _data["description"];
            this.unit = _data["unit"];
            this.quantity = _data["quantity"];
            this.unitPrice = _data["unitPrice"];
            this.vatRate = _data["vatRate"];
            this.invoiceId = _data["invoiceId"];
            this.rowVersion = _data["rowVersion"];
            this.netAmount = _data["netAmount"];
            this.grossAmount = _data["grossAmount"];
        }
    }

    static fromJS(data: any): InvoiceItemDTO {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceItemDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["description"] = this.description;
        data["unit"] = this.unit;
        data["quantity"] = this.quantity;
        data["unitPrice"] = this.unitPrice;
        data["vatRate"] = this.vatRate;
        data["invoiceId"] = this.invoiceId;
        data["rowVersion"] = this.rowVersion;
        data["netAmount"] = this.netAmount;
        data["grossAmount"] = this.grossAmount;
        return data;
    }
}

export interface IInvoiceItemDTO {
    id?: number;
    description?: string;
    unit?: string;
    quantity?: number;
    unitPrice?: number;
    vatRate?: number;
    invoiceId?: number;
    rowVersion?: string;
    netAmount?: number;
    grossAmount?: number;
}

export class InvoiceItemUpdateDTO implements IInvoiceItemUpdateDTO {
    description?: string;
    unit?: string;
    quantity?: number;
    unitPrice?: number;
    vatRate?: number;

    constructor(data?: IInvoiceItemUpdateDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.description = _data["description"];
            this.unit = _data["unit"];
            this.quantity = _data["quantity"];
            this.unitPrice = _data["unitPrice"];
            this.vatRate = _data["vatRate"];
        }
    }

    static fromJS(data: any): InvoiceItemUpdateDTO {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceItemUpdateDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["description"] = this.description;
        data["unit"] = this.unit;
        data["quantity"] = this.quantity;
        data["unitPrice"] = this.unitPrice;
        data["vatRate"] = this.vatRate;
        return data;
    }
}

export interface IInvoiceItemUpdateDTO {
    description?: string;
    unit?: string;
    quantity?: number;
    unitPrice?: number;
    vatRate?: number;
}

export class PagedResponseOfListOfInvoiceDTO implements IPagedResponseOfListOfInvoiceDTO {
    data?: InvoiceDTO[] | undefined;
    pageNumber?: number;
    pageSize?: number;
    totalCount?: number;
    totalPages?: number;

    constructor(data?: IPagedResponseOfListOfInvoiceDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(InvoiceDTO.fromJS(item));
            }
            this.pageNumber = _data["pageNumber"];
            this.pageSize = _data["pageSize"];
            this.totalCount = _data["totalCount"];
            this.totalPages = _data["totalPages"];
        }
    }

    static fromJS(data: any): PagedResponseOfListOfInvoiceDTO {
        data = typeof data === 'object' ? data : {};
        let result = new PagedResponseOfListOfInvoiceDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item ? item.toJSON() : undefined as any);
        }
        data["pageNumber"] = this.pageNumber;
        data["pageSize"] = this.pageSize;
        data["totalCount"] = this.totalCount;
        data["totalPages"] = this.totalPages;
        return data;
    }
}

export interface IPagedResponseOfListOfInvoiceDTO {
    data?: InvoiceDTO[] | undefined;
    pageNumber?: number;
    pageSize?: number;
    totalCount?: number;
    totalPages?: number;
}

export class InvoiceDTO implements IInvoiceDTO {
    id?: number;
    invoiceNumber?: string;
    customerName?: string;
    customerBusinessId?: string | undefined;
    issueDate?: string;
    dueDate?: string;
    status?: InvoiceStatus;
    currencyCode?: string;
    rowVersion?: string;
    items?: InvoiceItemDTO[];
    totalNet?: number;
    totalGross?: number;

    constructor(data?: IInvoiceDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.invoiceNumber = _data["invoiceNumber"];
            this.customerName = _data["customerName"];
            this.customerBusinessId = _data["customerBusinessId"];
            this.issueDate = _data["issueDate"];
            this.dueDate = _data["dueDate"];
            this.status = _data["status"];
            this.currencyCode = _data["currencyCode"];
            this.rowVersion = _data["rowVersion"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(InvoiceItemDTO.fromJS(item));
            }
            this.totalNet = _data["totalNet"];
            this.totalGross = _data["totalGross"];
        }
    }

    static fromJS(data: any): InvoiceDTO {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["invoiceNumber"] = this.invoiceNumber;
        data["customerName"] = this.customerName;
        data["customerBusinessId"] = this.customerBusinessId;
        data["issueDate"] = this.issueDate;
        data["dueDate"] = this.dueDate;
        data["status"] = this.status;
        data["currencyCode"] = this.currencyCode;
        data["rowVersion"] = this.rowVersion;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        data["totalNet"] = this.totalNet;
        data["totalGross"] = this.totalGross;
        return data;
    }
}

export interface IInvoiceDTO {
    id?: number;
    invoiceNumber?: string;
    customerName?: string;
    customerBusinessId?: string | undefined;
    issueDate?: string;
    dueDate?: string;
    status?: InvoiceStatus;
    currencyCode?: string;
    rowVersion?: string;
    items?: InvoiceItemDTO[];
    totalNet?: number;
    totalGross?: number;
}

export enum InvoiceStatus {
    Issued = 0,
    Sent = 1,
    Paid = 2,
    Overdue = 3,
    Cancelled = 4,
}

export enum ConditionType {
    Equals = "Equals",
    GreaterThan = "GreaterThan",
    LessThan = "LessThan",
    GreaterThanOrEqual = "GreaterThanOrEqual",
    LessThanOrEqual = "LessThanOrEqual",
    Between = "Between",
    StartsWith = "StartsWith",
    Contains = "Contains",
    In = "In",
    NotIn = "NotIn",
    NotEquals = "NotEquals",
    EndsWith = "EndsWith",
    IsNull = "IsNull",
    IsNotNull = "IsNotNull",
}

export enum SortDirection {
    Asc = 0,
    Desc = 1,
}

export class InvoiceCreateDTO implements IInvoiceCreateDTO {
    invoiceNumber?: string;
    customerName?: string;
    customerBusinessId?: string | undefined;
    issueDate?: string;
    dueDate?: string;
    status?: InvoiceStatus;
    currencyCode?: string;
    items?: InvoiceItemCreateDTO[];

    constructor(data?: IInvoiceCreateDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.invoiceNumber = _data["invoiceNumber"];
            this.customerName = _data["customerName"];
            this.customerBusinessId = _data["customerBusinessId"];
            this.issueDate = _data["issueDate"];
            this.dueDate = _data["dueDate"];
            this.status = _data["status"];
            this.currencyCode = _data["currencyCode"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(InvoiceItemCreateDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): InvoiceCreateDTO {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceCreateDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["invoiceNumber"] = this.invoiceNumber;
        data["customerName"] = this.customerName;
        data["customerBusinessId"] = this.customerBusinessId;
        data["issueDate"] = this.issueDate;
        data["dueDate"] = this.dueDate;
        data["status"] = this.status;
        data["currencyCode"] = this.currencyCode;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IInvoiceCreateDTO {
    invoiceNumber?: string;
    customerName?: string;
    customerBusinessId?: string | undefined;
    issueDate?: string;
    dueDate?: string;
    status?: InvoiceStatus;
    currencyCode?: string;
    items?: InvoiceItemCreateDTO[];
}

export class InvoiceItemCreateDTO implements IInvoiceItemCreateDTO {
    description?: string;
    unit?: string;
    quantity?: number;
    unitPrice?: number;
    vatRate?: number;

    constructor(data?: IInvoiceItemCreateDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.description = _data["description"];
            this.unit = _data["unit"];
            this.quantity = _data["quantity"];
            this.unitPrice = _data["unitPrice"];
            this.vatRate = _data["vatRate"];
        }
    }

    static fromJS(data: any): InvoiceItemCreateDTO {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceItemCreateDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["description"] = this.description;
        data["unit"] = this.unit;
        data["quantity"] = this.quantity;
        data["unitPrice"] = this.unitPrice;
        data["vatRate"] = this.vatRate;
        return data;
    }
}

export interface IInvoiceItemCreateDTO {
    description?: string;
    unit?: string;
    quantity?: number;
    unitPrice?: number;
    vatRate?: number;
}

export class InvoiceUpdateDTO implements IInvoiceUpdateDTO {
    invoiceNumber?: string;
    customerName?: string;
    customerBusinessId?: string | undefined;
    issueDate?: string;
    dueDate?: string;
    status?: InvoiceStatus;
    currencyCode?: string;

    constructor(data?: IInvoiceUpdateDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.invoiceNumber = _data["invoiceNumber"];
            this.customerName = _data["customerName"];
            this.customerBusinessId = _data["customerBusinessId"];
            this.issueDate = _data["issueDate"];
            this.dueDate = _data["dueDate"];
            this.status = _data["status"];
            this.currencyCode = _data["currencyCode"];
        }
    }

    static fromJS(data: any): InvoiceUpdateDTO {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceUpdateDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["invoiceNumber"] = this.invoiceNumber;
        data["customerName"] = this.customerName;
        data["customerBusinessId"] = this.customerBusinessId;
        data["issueDate"] = this.issueDate;
        data["dueDate"] = this.dueDate;
        data["status"] = this.status;
        data["currencyCode"] = this.currencyCode;
        return data;
    }
}

export interface IInvoiceUpdateDTO {
    invoiceNumber?: string;
    customerName?: string;
    customerBusinessId?: string | undefined;
    issueDate?: string;
    dueDate?: string;
    status?: InvoiceStatus;
    currencyCode?: string;
}

export class PaginationOfInvoice implements IPaginationOfInvoice {
    pageIndex?: number;
    pageSize?: number;
    count?: number;
    data?: Invoice[];

    constructor(data?: IPaginationOfInvoice) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.pageIndex = _data["pageIndex"];
            this.pageSize = _data["pageSize"];
            this.count = _data["count"];
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(Invoice.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PaginationOfInvoice {
        data = typeof data === 'object' ? data : {};
        let result = new PaginationOfInvoice();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["pageIndex"] = this.pageIndex;
        data["pageSize"] = this.pageSize;
        data["count"] = this.count;
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IPaginationOfInvoice {
    pageIndex?: number;
    pageSize?: number;
    count?: number;
    data?: Invoice[];
}

export class BaseEntity implements IBaseEntity {
    id?: number;

    constructor(data?: IBaseEntity) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): BaseEntity {
        data = typeof data === 'object' ? data : {};
        let result = new BaseEntity();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data;
    }
}

export interface IBaseEntity {
    id?: number;
}

export class Invoice extends BaseEntity implements IInvoice {
    invoiceNumber?: string;
    customerName?: string;
    customerBusinessId?: string | undefined;
    issueDate?: string;
    dueDate?: string;
    status?: InvoiceStatus;
    currencyCode?: string;
    rowVersion?: string;
    items?: InvoiceItem[];

    constructor(data?: IInvoice) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.invoiceNumber = _data["invoiceNumber"];
            this.customerName = _data["customerName"];
            this.customerBusinessId = _data["customerBusinessId"];
            this.issueDate = _data["issueDate"];
            this.dueDate = _data["dueDate"];
            this.status = _data["status"];
            this.currencyCode = _data["currencyCode"];
            this.rowVersion = _data["rowVersion"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(InvoiceItem.fromJS(item));
            }
        }
    }

    static override fromJS(data: any): Invoice {
        data = typeof data === 'object' ? data : {};
        let result = new Invoice();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["invoiceNumber"] = this.invoiceNumber;
        data["customerName"] = this.customerName;
        data["customerBusinessId"] = this.customerBusinessId;
        data["issueDate"] = this.issueDate;
        data["dueDate"] = this.dueDate;
        data["status"] = this.status;
        data["currencyCode"] = this.currencyCode;
        data["rowVersion"] = this.rowVersion;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IInvoice extends IBaseEntity {
    invoiceNumber?: string;
    customerName?: string;
    customerBusinessId?: string | undefined;
    issueDate?: string;
    dueDate?: string;
    status?: InvoiceStatus;
    currencyCode?: string;
    rowVersion?: string;
    items?: InvoiceItem[];
}

export class InvoiceItem extends BaseEntity implements IInvoiceItem {
    description?: string;
    unit?: string;
    quantity?: number;
    unitPrice?: number;
    vatRate?: number;
    invoiceId?: number;
    rowVersion?: string;
    invoice?: Invoice;

    constructor(data?: IInvoiceItem) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.description = _data["description"];
            this.unit = _data["unit"];
            this.quantity = _data["quantity"];
            this.unitPrice = _data["unitPrice"];
            this.vatRate = _data["vatRate"];
            this.invoiceId = _data["invoiceId"];
            this.rowVersion = _data["rowVersion"];
            this.invoice = _data["invoice"] ? Invoice.fromJS(_data["invoice"]) : undefined as any;
        }
    }

    static override fromJS(data: any): InvoiceItem {
        data = typeof data === 'object' ? data : {};
        let result = new InvoiceItem();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["description"] = this.description;
        data["unit"] = this.unit;
        data["quantity"] = this.quantity;
        data["unitPrice"] = this.unitPrice;
        data["vatRate"] = this.vatRate;
        data["invoiceId"] = this.invoiceId;
        data["rowVersion"] = this.rowVersion;
        data["invoice"] = this.invoice ? this.invoice.toJSON() : undefined as any;
        super.toJSON(data);
        return data;
    }
}

export interface IInvoiceItem extends IBaseEntity {
    description?: string;
    unit?: string;
    quantity?: number;
    unitPrice?: number;
    vatRate?: number;
    invoiceId?: number;
    rowVersion?: string;
    invoice?: Invoice;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}